### ISSUE TITLE
Direct .torrent links from RARBG are considered "invalid"

### ISSUE THREAD

**Issue by Cormak** [proninyaroslav/libretorrent#104]
1) Copy a direct torrent link from https://rarbg.to (not the magnet but the direct links ending in .torrent)
2) Paste said link into Libretorrent's "add link" feature
3) Get a message saying "Link invalid"

These links open perfectly fine when you paste them into qBittorrent or Transmission but not Libretorrent.

**Comment by proninyaroslav** [comment]
Hello. To check URL, I use regular expression provided by the standard Android library. It turns out that it does not recognize square brackets in URL (more precisely in the filename `... -[rarbg.to] ...`).
I think that I will have to use my variant of regular expression, or use regular expression from qBittorrent.
