### ISSUE TITLE
Some Changes Expected

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [proninyaroslav/libretorrent#116]
Please Change The Layout To The Tab Layout Which Is Easy To Use

Please Disable The Notifications When No Torrents Are Going On

Please WiFi Only Download Settings

**Comment by proninyaroslav** [comment]
1) This complicates the code and increases memory consumption, this is a dubious improvement.
2) Ok.
3) Already exist https://github.com/proninyaroslav/libretorrent/issues/20

**Comment by proninyaroslav** [comment]
On the second point: if you mean the foreground notification that is displayed when app is launched, it can't be hidden, because it determines the running of the running background service, which has the ability to download torrents. Without this notification, this service can be killed by system at any time.

**Comment by gedling** [comment]
I think for the second point it's okay for a  notification to open when the app is launched but if you leave the app and it's still not downloading anything the notification stays open which seems unnecessary.

**Comment by proninyaroslav** [comment]
@gedling It is probably better to make option "Work in the background". If the option is disabled, then the app completely closes after window has been destroyed.

**Comment by Jithendra-V-Kumar** [comment]
This App Uses More Memory And Battery As Compared To Other Torrents For Android

So It Is Advised To Avoid  The Sticky Notification On Notification Bar And Only Show This Notifications When Only Any Torrent Operations Are Going On

I Know That These Notifications Are Used To Prevent The Service Being Killed By The System.

But Any Torrents Not going on there is no need of preventing from this killing

The other Torrents Like Flud Torrent , Fu Torrent ,Etc Uses This Option Which Help Them To Reduce heir Apps Memory And Battery Usage

**Comment by PiwwowPants** [comment]
I put in a pull request for 2 here https://github.com/proninyaroslav/libretorrent/pull/150 

I agree with your assessment. A toggle is needed though because potential heavy users would want this application running non-stop and watching a  directory for torrents. I assume regular, adhoc users would just want the app to be removed from the background like normal though.

**Comment by proninyaroslav** [comment]
Implemented.
