### ISSUE TITLE
Needs to show AVAILABILITY info

### ISSUE THREAD

**Issue by Pidus** [proninyaroslav/libretorrent#123]
It would be better if the app shows the torrent 'AVAILABILITY' information in the 'STATE' tab. This will help users to know whether a file can be downloaded or not.

Latest update is great. Thank you.

**Comment by proninyaroslav** [comment]
Hi. I didn't quite understand the purpose of `availability`. What exactly should it contain and how to look?

**Comment by Cormak** [comment]
@proninyaroslav Availability is how available the target file(s) is on the swarm. It will be 100% if somebody in the swarm has 100% of the original file(s). It is useful because if you go to a swarm and the availability is less than 100% you can move on to another torrent that has 100% of the file(s) you want instead of sitting on a swarm and never getting 100% of the files you want. (eg. everybody in the swarm only has 35% of the file because the seeder left too early)

You can see this function in every desktop torrent client, but I'm not familiar with where that function is on libtorrent. You may want to consult the devs of that lib.

**Comment by proninyaroslav** [comment]
@Cormak I used `transmission` and `qbittorrent`, and I did not find this information. Can you specify a concrete client?

**Comment by Pidus** [comment]
Flud has this.

**Comment by proninyaroslav** [comment]
Ok.

**Comment by proninyaroslav** [comment]
Added  ac48fee.
