### ISSUE TITLE
App notification just says "network status:online" twice on MIUI 

### ISSUE THREAD

**Issue by Pidus** [proninyaroslav/libretorrent#124]
OS : MIUI 9, Android 7.1.1 
Instead of showing DL/UP speeds or other useful info, the app notification gives unnecessary info. This is a MIUI specific issue (MIUI mess up Android notifications quite bad), not LibreTorrent's fault. Just looks bad. If possible, please fix it. 
![img_20171203_163945](https://user-images.githubusercontent.com/11857051/33524814-85d683e8-d81b-11e7-8da2-38859ffe4c4a.png)

**Comment by proninyaroslav** [comment]
Oh, I can't guarantee that I can fix it, it would be nice to know the reason for this error at the MIUI level. How much I understand MIUI launcher doesn't show expanded notifications? Does this happen with all applications?

**Comment by proninyaroslav** [comment]
Here you can see normal behaviour of the notification:
![screenshot_1512300977](https://user-images.githubusercontent.com/7840559/33525017-c7f65db8-d837-11e7-9cdb-d0b0be0e358d.png)![screenshot_1512301114](https://user-images.githubusercontent.com/7840559/33525018-c81833d4-d837-11e7-967b-bc8b5243c05a.png)

**Comment by Pidus** [comment]
Flud didn't have this issue. I have uninstalled it so can't give any screen shot.
This is how `advanced download manager` notification looks: 
![img_20171203_171336](https://user-images.githubusercontent.com/11857051/33525057-7fcd4fd2-d81f-11e7-8550-729a1e9a379d.png)
Another thing, if I expand the notification the problem goes away. But that is a tedious process in MIUI.
![screenshot_2017-12-03-17-13-51-122_com miui home](https://user-images.githubusercontent.com/11857051/33525067-b22f4228-d81f-11e7-8db6-3fab0a8359ab.png)

**Comment by proninyaroslav** [comment]
It looks like a cropped inbox style. I think in this situation nothing to do: for create a notification I using the API, which is provided to developers on Android, but the GUI (launcher) developer for android has the right to change the mechanism that is hidden behind the API. As we know, prior to version 4.1 the following notification style was used:

![33525017-c7f65db8-d837-11e7-9cdb-d0b0be0e358d](https://user-images.githubusercontent.com/7840559/33526519-dacbff9e-d853-11e7-8cb9-049752457c3e.png)

This style is used to this day and I use it to output a basic notification if no torrent is added, and `content text` use for showing the network status. But since version 4.1 there is an "extended" style of notifications, which allows you to store more information:

![33525018-c81833d4-d837-11e7-967b-bc8b5243c05a](https://user-images.githubusercontent.com/7840559/33526531-0bbdad6e-d854-11e7-9d30-d87b2bb7c1a4.png)

In it appeared such a thing as `summary text`, which allows you to output additional information. I use it to show the network status, because the new style doesn't  have space for its output in `content text`.

Ss far as I understand, by default MIUI hides `multiline content` in inbox style (although it looks like shit on MIUI), but does not hide `summary text` with network status. But most importantly, MIUI mixes inbox style and default style in one notification, which contradicts the original idea of the Android developers: usually if the app developer decided to create an inbox style notification, the default style is used on the lock screen to show the minimum necessary information. This parameter can be configured in the Android settings. In the case of MIUI, they simply broke the system. I will look for information on this issue, maybe there have been similar cases. And I think it's worth contacting with the MIUI developers, if possible.

**Comment by Pidus** [comment]
Thanks for the explaining the situation. :) 
Because of crappy UI decisions like this, MIUI is hated. Hope they do something about it like they promised in the near future.
