### ISSUE TITLE
Even WiFi Only Mode Turned But Downloading With Cellular Data

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [proninyaroslav/libretorrent#128]
1) I Have Turned On The WiFi Only Option The Torrents Are But Started To Download Through The Cellular Data

And It Is Advised To Show A Message That What Network You Would Like To Use For The Torrent Downloads When First Tie Opens The App

  
2) With The Option To Shut Down The Apps After the Torrents Have Finished Please Add another Option To  Turn Off The Cellular Data And WiFi Too..... Which May Be Helpful

**Comment by proninyaroslav** [comment]
Only wi-fi option works, but there is one bug: it does not check if the wi-fi is connected to access point.

**Comment by PiwwowPants** [comment]
The bug part of this post should be addressed in PR https://github.com/proninyaroslav/libretorrent/pull/129.

This change made it so the WifiReceiver is checking wifi connectivity when deciding if it should pause/start downloads rather than just the wifi's state on the device.

The enhancement portions (the second two mentions) of this were not addressed.

**Comment by proninyaroslav** [comment]
Fixed.
