### ISSUE TITLE
Error In Showing The Torrent's Downloaded Size

### ISSUE THREAD

**Issue by Jithendra-V-Kumar** [proninyaroslav/libretorrent#133]
In The Torrent State 
The Downloaded Size Sometimes Showing More Than The Actual Total Size Of The File

For Example  697MB Is To Be Downloaded It Showing As 700MB Or Else

**Comment by PiwwowPants** [comment]
Difficult to test without knowing a download that would cause this. My guess is that since we're formatting longs down to strings without decimals, there is a rounding issue that Math.floor could fix. My question is, have you actually seen a download that is displaying 3MB more than it should (700MB/697MB in your example) or have they mostly just been 1MB?

**Comment by proninyaroslav** [comment]
The mechanism of bittorrent is that the file is divided into pieces, so a person who wants to download only some files from the torrrent, in order to maintain the integrity of the pieces, a small amount of redundant (for him) information will also be kept.
There is no mistake in this.
