### ISSUE TITLE
Please Add An Applocking Settings Within This App

### ISSUE THREAD

**Issue by IamJithendra** [proninyaroslav/libretorrent#134]
If Such An Option Is Is Implemented . The Users Don't Need To Use Any App Locks And Then This Will A Great Useful Implementation For The Users And Then This Is A New Feature That Were Not Available On Other More Torrent Apps For Android ( Only Some Apps Has This Feature )

**Comment by proninyaroslav** [comment]
That is you have to offer to protect app from using other people other than the owner?

**Comment by PiwwowPants** [comment]
This feature feels a little backwards. The application does not really store sensitive data. If you're downloading something that you'd rather keep private, you could just change the name of the download to something ambiguous and use a file manager that has app locking.

Maybe it'd still reveal information by letting others in to see the names of the files being downloaded, but I think that's a little extraneous since the information can still not be accessed, just the file name. The only thing that would be exposed is something embarrassing, not something destructively sensitive.

**Comment by proninyaroslav** [comment]
@PiwwowPants we can try to do it, but when the whole conceived functionality will be implemented.
