### ISSUE TITLE
Add option for custom battery limit

### ISSUE THREAD

**Issue by noughtmare** [proninyaroslav/libretorrent#141]
It would be nice to be able to add a custom battery percentage limit. I would like my torrents to stop at 50% charge (or maybe even higher), so that is not really when the battery is low.

**Comment by proninyaroslav** [comment]
This will require constant monitoring of the battery that will negatively affect its charge. 15% is the standard charge at which the BATTERY_LOW event is dispatched.

**Comment by PiwwowPants** [comment]
It would likely consume more battery still, but the method TorrentDownload.alert is called non-stop while downloading already since it is waiting for changes to the state of the download. A check can just be done there and switch the type to TORRENT_PAUSED if the battery is too low.

I'm looking to see its impact now (already have the preference and conditional checks), but I think if we did want this, the best way would be to add an extra settings called "Custom Battery Percentage" that lets the user unlock the battery percentage threshold from the normal 15% limit. When it's set, we can warn the user that it'll adversely affect the battery life with a dialog.

**Comment by PiwwowPants** [comment]
I just put in pull request https://github.com/proninyaroslav/libretorrent/pull/147 for this.

It will definitely consume additional battery, because it now has to receive the battery changed status from the operating system. I am not convinced it will consume a greater deal than normal though since the app is already continuously checking the status of the downloads anyway.

**Comment by proninyaroslav** [comment]
Implemented.
