### ISSUE TITLE
Add a magnet instantly

### ISSUE THREAD

**Issue by fparri** [proninyaroslav/libretorrent#22]
Add the abilità to add a magnetico link instantly, without the programma needing to first 'resolve' it. This is quote useful when you have several magnet links to add.

**Comment by proninyaroslav** [comment]
Can be put magnet links into queue for processing, without waiting.

**Comment by JohnVeness** [comment]
This would be useful on torrents with very few seeders. I've had some magnet links that I've had to add to a desktop torrent client (e.g. deluge) which have taken several tens of minutes before they've started even showing the list of files or even the total size, which I assume is due to lack of seeders (I'm no expert). I wasn't able to add them to libretorrent at all, as it just timed out.

**Comment by Salamandar** [comment]
YES ! I was gonna open this issue when I saw yours.

**Comment by proninyaroslav** [comment]
This will require a serious redesign of the mechanism for adding torrents. As an option, I propose to make the maximum waiting time customizable.

**Comment by dessalines** [comment]
@proninyaroslav I recommend looking at how `qbittorrent` handles this. They have an interface when you add a torrent, that says "fetching metadata", and file selection shows up after its done, but its not necessary to add the torrent.

**Comment by proninyaroslav** [comment]
@dessalines 
I will try to implement it.

**Comment by proninyaroslav** [comment]
Implemented in 1.4 version.
