### ISSUE TITLE
Possible to select between add and pause button in notification drawer

### ISSUE THREAD

**Issue by remenraj** [proninyaroslav/libretorrent#29]

**Comment by proninyaroslav** [comment]
Hello. Can you substantiate your proposal?

**Comment by remenraj** [comment]
Yeah like whenever I'm browsing It's easy for me if there's a pause all/resume all button in the notification drawer so that I don't have to go into the app and Pause the active torrents. Also Shutdown works as well but the problem with that is it removes the app notification from the drawer and I have to go through my apps and open it again.

**Comment by proninyaroslav** [comment]
Shutdown is designed to completely close app. About pause: I think need a vote for the inclusion of this feature.

**Comment by Cormak** [comment]
I agree with this. It's the same concept as putting a pause button in the notification for a music player. You want to stop a process quickly without going into the app. I don't really see the need for an "add" button in the notification since adding a torrent will usually happen via the Android intents system from another app, such as clicking a torrent or magnet link on your web browser and the prompt saying "open with Libretorrent?"

**Comment by proninyaroslav** [comment]
I will make it possible to select between add button and pause button.

**Comment by proninyaroslav** [comment]
Added.
